# Change these first
owner: nicholasvdb # Your GitHub organization or username, where this repository lives
repo: ichoosr-status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: ENNL API
    url: https://api-ennl.ichoosr.com
    country: Netherlands
  - name: SPNL API
    url: https://api-spnl.ichoosr.com
  - name: TPNL API
    url: https://api-tpnl.ichoosr.com
  - name: ECNL API
    url: https://api-ecnl.ichoosr.com
  - name: ENBE API
    url: https://api-enbe.ichoosr.com
  - name: SPBE API
    url: https://api-spbe.ichoosr.com
  - name: REBE API
    url: https://api-rebe.ichoosr.com
  - name: ENUK API
    url: https://api-enuk.ichoosr.com
  - name: SPUK API
    url: https://api-spuk.ichoosr.com
  - name: ENUS API
    url: https://api-enus.ichoosr.com
  - name: ENJP API
    url: https://api-enjp.ichoosr.com
  - name: SPJP API
    url: https://api-spjp.ichoosr.com
  - name: ENNL APP
    url: https://app-ennl.ichoosr.com
  - name: SPNL APP
    url: https://app-spnl.ichoosr.com
  - name: TPNL APP
    url: https://internetcollectief.eigenhuis.nl
  - name: ECNL APP
    url: https://samen.nl
  - name: ENBE APP
    url: https://ichoosr.be/energie/ichoosr/home
  - name: SPBE APP
    url: https://ichoosr.be/zonnepanelen/
  - name: REBE APP
    url: https://ichoosr.be/thuisbatterij/
  - name: ENUK APP
    url: https://bigcommunityswitch.co.uk
  - name: SPUK APP
    url: https://solartogether.co.uk
  - name: ENJP APP
    url: https://group-buy.metro.tokyo.lg.jp
  - name: SPJP APP
    url: https://group-buy.jp/solar
  - name: Backoffice
    url: https://backoffice.ichoosr.com
  - name: CMS API
    url: https://content.ichoosr.com
  - name: Mailer API
    url: https://mailer.ichoosr.com/swagger/index.html
  - name: Identity
    url: https://identity.ichoosr.com/
  - name: Payments API
    url: https://payments.ichoosr.com/swagger/index.html
  - name: Forms API
    url: https://forms.ichoosr.com/
    assignees:
      - drikusroor
  - name: Offers API
    url: https://offers.ichoosr.com/
    assignees:
      - drikusroor
  - name: Profiles API
    url: https://profiles.ichoosr.com/
  - name: RealTime API
    url: https://real-time.ichoosr.com/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ichoosr-status
  logoUrl: https://raw.githubusercontent.com/nicholasvdb/ichoosr-status/master/assets/favicon.ico
  name: "iChoosr Status Pages"
  introTitle: "**iChoosr Status Pages**"
  introMessage: This is a status page that monitors all the iChoosr websites and applications, shows when a website goes offline, and creates an issue accordingly.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  js: "class SearchBar { searchInput = null; constructor() { window.addEventListener('load', this.init.bind(this)); } init() { this.setupElements(); this.addEventListeners(); } setupElements() { this.searchInput = this.createSearchBar(); this.updateSites(); } updateSites() { this.sites = document.querySelectorAll('section.live-status article.link'); } addEventListeners() { this.searchInput.addEventListener( 'input', this.handleSearchInputChange.bind(this) ); } handleSearchInputChange(e) { this.updateSites(); const value = e.target.value; this.sites.forEach((siteEl) => { let match = false; const headingEl = siteEl.querySelector('h4 a'); const heading = headingEl.innerHTML; const href = headingEl.getAttribute('href'); if (!value) { match = true; } else { if (heading.toLowerCase().includes(value.toLowerCase())) { match = true; } else if ( href && href.toLowerCase().includes(value && value.toLowerCase()) ) { match = true; } } if (match) { siteEl.style.display = 'block'; } else { siteEl.style.display = 'none'; } }); } createSearchBar() { const listItem = document.createElement('li'); const searchInput = document.createElement('input'); searchInput.setAttribute('type', 'search'); searchInput.setAttribute('placeholder', 'Search'); searchInput.classList.add('search-bar'); searchInput.style.padding = '.5em'; const navItems = document.querySelector('nav ul'); listItem.appendChild(searchInput); navItems.appendChild(listItem); return searchInput; } } new SearchBar();"
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
